// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLx4adz4gow391gM1SJ65uN0NUh-P6oZg',
    appId: '1:1032544414454:web:fe56b5a3ffe72a8ac81ad7',
    messagingSenderId: '1032544414454',
    projectId: 'homepets-c02ac',
    authDomain: 'homepets-c02ac.firebaseapp.com',
    storageBucket: 'homepets-c02ac.appspot.com',
    measurementId: 'G-1R4F7E8FCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTZxQbacyXMzSnjRy_ZxnjLq--JdeGY1w',
    appId: '1:1032544414454:android:debe3ac63e98161cc81ad7',
    messagingSenderId: '1032544414454',
    projectId: 'homepets-c02ac',
    storageBucket: 'homepets-c02ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3FFYDbEE1O0D-d9DXo49vA2fudeJcR-I',
    appId: '1:1032544414454:ios:3255551643e29802c81ad7',
    messagingSenderId: '1032544414454',
    projectId: 'homepets-c02ac',
    storageBucket: 'homepets-c02ac.appspot.com',
    iosClientId: '1032544414454-oncg6q06q917n5id5qv50unr2ndnscj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject',
  );
}
